###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9kb3BlZHJvIiwiaWQiOiI2NDVhY2Y1NTJjYjdmNTc0ZmI0YzJmYzgiLCJpYXQiOjE2ODQwMDE4NjAsImV4cCI6MTY4NDAwNTQ2MH0.kO0aSGHw4YPw5ptXCJmPDF96F6JP5sg7_lOqQeCBzUk

{
    "title": "Doing this for the test of it, this is some more test from the warden of the North",
    "author": "Odo Pedro Chidi",
    "url" : "http://localhost:3003/api/blogs",
    "likes": 5,
    "userId": "645acf112cb7f574fb4c2fc0"
}

###
GET http://localhost:3003/api/blogs HTTP/1.1


###
PUT http://localhost:3003/api/blogs/6461a54240a19896d7c1623c HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9kb3BlZHJvIiwiaWQiOiI2NDVhY2Y1NTJjYjdmNTc0ZmI0YzJmYzgiLCJpYXQiOjE2ODQyNzA5OTAsImV4cCI6MTY4NDI3NDU5MH0.SWwxVSmXQFX-Fio7ukQ2coDmbdmGU2o8o9z5ComWrgQ

{
"title": "The warden of the North, proposes",
"author": "Odo Peter Ebere",
"url": "http://localhost:3003/api/blogs",
"likes": 5
}
###

DELETE http://localhost:3003/api/blogs/645c3de0d8a5df484d8787bf HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9kb3BlZHJvIiwiaWQiOiI2NDVhY2Y1NTJjYjdmNTc0ZmI0YzJmYzgiLCJpYXQiOjE2ODQyNzA5OTAsImV4cCI6MTY4NDI3NDU5MH0.SWwxVSmXQFX-Fio7ukQ2coDmbdmGU2o8o9z5ComWrgQ


//////user REST

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "Sir Hodor",
    "name": "Hodor Snow",
    "password": "123456"
}


###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "Odopedro",
    "name": "Odo Pedro Ebere",
    "password": "123456"
}