###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "How to become a top notch developer and earn yourself some shillings by yours truly, the warden of the north",
    "author": "Odo Peter Ebere",
    "url" : "http://localhost:3003/api/blogs",
    "likes": 2
}

###
GET http://localhost:3003/api/blogs/63f485936e1c1df04156dc63 HTTP/1.1


###
PUT http://localhost:3003/api/blogs/63f485936e1c1df04156dc63 HTTP/1.1
content-type: application/json

{
"title": "This is another blog post sent to the database from the rest client of VScode, this is speaking about how I am improving my backend skills and my technical writing skills, which seems to be doing terrible at the moment",
"author": "Odo Peter Ebere",
"url": "http://localhost:3003/api/blogs",
"likes": 2
}